public class Main {
    public static void main(String[] args) {
        System.out.println("Hello world!");
        int number = 2;
        System.out.println(number);
        byte g = 12;
        System.out.println(g);
        short x = 10000;
        System.out.println(x);
        long y =-20;
        System.out.println(y);
        float a = 4.88888888f;
        System.out.println(a);
        float b = (float) 4.88888888;
        System.out.println(b);
        double t = 4.88888888;
        System.out.println(t);
        double weightFirst = 78.2;
        double weightSecond = 82.7;
        double general = weightFirst + weightSecond;
        System.out.println ( "Общий вес " + general + " кг");
        double difference = Math.abs (weightSecond - weightFirst);
        System.out.println ("Разница между весом " + difference + " кг");
int bananas = 5;
int oneBananas = 80;
int bananaWeight = oneBananas * bananas;
System.out.println("вес бананов "+ bananaWeight + " г");
int milk = 200;
int oneHundredMilk = 105;
int milkweight = milk * oneHundredMilk / 100;
System.out.println("Вес молока "+ milkweight + " г");
int iceCream = 2;
int oneIceCream = 100;
int iceCreamWeight = iceCream * oneIceCream;
System.out.println( "Вес мороженного "+ iceCreamWeight+ " г");
int egg = 4;
int oneEgg = 70;
int eggWeidht = egg * oneEgg;
        System.out.println ("вес яиц " + eggWeidht + " г");
        float breakfastWeight = bananaWeight + milkweight + iceCreamWeight + eggWeidht;
        System.out.println ("Вес завтрака "+ breakfastWeight + " г");
float breakfastWeightInKg = breakfastWeight / 1000;
        System.out.println ("Вес затрака "+ breakfastWeightInKg + " кг");
int reset = 7;
int resetIng = reset * 1000;
int resetOneDay = 250;
int day = resetIng / resetOneDay;
System.out.println( "Если спорсмен будет терять по 250г в день, то уйдет " + day + " дн");
int resetDay = 500;
int dayFiveHundred = resetIng / resetDay;
System.out.println("Если спорсмен будет терять по 500 гр в день, то уйдет "+ dayFiveHundred + " дн");
int maxReset = resetOneDay + resetDay;
   int average = maxReset / 2;
   double averageDay =  resetIng / average;
        System.out.println("В среднем потребуется "+ averageDay + " дн");
int masha = 67760;
int denis = 83690;
int kristina = 76230;
double upMasha = masha * 0.1;
double afterUpMasha = masha + upMasha;
        System.out.println("зарплата Маши после повышения "+ afterUpMasha+ " рублей");
double upDenis = denis * 0.1;
double afterupdenis = denis + upDenis;
        System.out.println("зарплата Дениса после повышения " + afterupdenis+ " рублей");
double upKristina = kristina * 0.1;
double afterUpKristina = kristina + upKristina;
        System.out.println("зарплата Кристины после повышения " + afterUpKristina+ " рублей");
int year = 12;
int yearMasha = masha * year;
double yearMashaAfterUp = afterUpMasha * year;
double differenceMasha = yearMashaAfterUp - yearMasha;
        System.out.println("Годовой доход Маши вырос на " + differenceMasha + " рублей");
        int yearDenis = denis * year;
        double yearDenisAfterUp = afterupdenis * year;
        double differenceDenis = yearDenisAfterUp - yearDenis;
        System.out.println("Годовой доход Дениса вырос на " +differenceDenis + " рублей" );
        int yearKristina = kristina * year;
        double yearKristinaAfterUp = afterUpKristina * year;
        double differenceKristina = yearKristinaAfterUp - yearKristina;
        System.out.println("Годовой доход Кристины вырос на " + differenceKristina + " рублей");
    }
}